#!/usr/bin/env python3
"""Emit a D1-ready SQL dump of the loaded database.

Usage:
    python scripts/db/dump_d1.py [--db PATH] [--out PATH] [--schema PATH]

Produces a single .sql file (PRAGMA-free apart from defer_foreign_keys,
idempotent: DROP + CREATE + INSERT) suitable for
`wrangler d1 execute <database> --file=<out> --remote`. D1 has no binary-DB
import; statements are the transport. Explicit BEGIN/COMMIT is NOT emitted --
D1 documents it as invalid inside `d1 execute --file` (it wraps execution in
its own implicit transaction); instead the file opens with
`PRAGMA defer_foreign_keys = ON`, so FK checks run at the end of wrangler's
implicit transaction and insert order across parent/child tables is safe
either way.

Publish flow (Phase A of db-migration-app-cutover-spec.md):
    python scripts/db/load.py            # rebuild data/wsob.db from raw+manual
    python scripts/db/check_fixture.py   # fixture parity gate
    python scripts/db/validate_db.py     # reconciliation gate
    python scripts/db/dump_d1.py         # emit dump.sql
    npx wrangler d1 execute <binding> --file=... --remote

Regenerating is always safe: the dump rebuilds every table from scratch.
"""

import argparse
import sqlite3
import sys
from pathlib import Path
from typing import Any

SCRIPTS_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = SCRIPTS_DIR.parent
DEFAULT_DB = REPO_ROOT / "data" / "wsob.db"
DEFAULT_SCHEMA = Path(__file__).resolve().parent / "schema.sql"
DEFAULT_OUT = REPO_ROOT / "data" / "wsob.d1.sql"

# Children before parents on DROP; creation order comes from schema.sql.
DROP_ORDER = [
    "live_sync_state",
    "position_overrides",
    "jersey_history_overrides",
    "trade_items",
    "trades",
    "transaction_items",
    "transactions",
    "keepers",
    "draft_picks",
    "player_season_ownership",
    "player_season_backfill",
    "player_team_season_points",
    "player_seasons",
    "players",
    "box_score_slots",
    "box_score_lines",
    "matchup_sides",
    "matchups",
    "team_owners",
    "teams",
    "retired_owners",
    "owners",
    "seasons",
    "mlb_teams",
]

# Tables retired from schema.sql that may still exist on the remote database
# from an earlier publish (the dump validates against the LOCAL db, which no
# longer has them). Dropped defensively: a leftover table carrying FK
# references to recreated parents fails the whole remote import with a
# FOREIGN KEY constraint error and rolls it back (hit 2026-08-25:
# player_season_points was created by the previous day's dump, then retired
# from the schema before the next full publish).
LEGACY_TABLES = [
    "player_season_points",
]


def quote(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return repr(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=DEFAULT_DB)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    con = sqlite3.connect(args.db)
    con.row_factory = sqlite3.Row
    try:
        tables = [
            r["name"]
            for r in con.execute(
                "SELECT name FROM sqlite_master WHERE type='table' "
                "AND name NOT LIKE 'sqlite_%'"
            )
        ]
        missing = set(tables) - set(DROP_ORDER)
        if missing:
            sys.exit(f"Tables present but not in DROP_ORDER: {sorted(missing)}")

        parts = [
            "-- Generated by scripts/db/dump_d1.py -- do not edit.",
            f"-- Source: {args.db.name}; publish with wrangler d1 execute.",
            "",
            # No explicit BEGIN/COMMIT: D1 documents them as invalid inside
            # `d1 execute --file` (it wraps execution in its own implicit
            # transaction). Deferring FK checks to that transaction's commit
            # gives the same all-or-nothing guarantee the per-table wrappers
            # used to pretend to, and makes parent/child insert order moot.
            "PRAGMA defer_foreign_keys = ON;",
            "",
        ]
        for table in DROP_ORDER:
            if table not in tables:
                continue
            parts.append(f"DROP TABLE IF EXISTS {table};")
        # Retired tables aren't in the local db, so the `tables` check above
        # skips them -- drop unconditionally in case remote still has one.
        for table in LEGACY_TABLES:
            parts.append(f"DROP TABLE IF EXISTS {table};")
        parts.append("")
        parts.append(args.schema.read_text())
        parts.append("")

        # Parents before children: harmless under defer_foreign_keys, but
        # keeps the dump loadable by plain sqlite3 too (which enforces FKs at
        # statement time when the pragma is absent).
        for table in reversed(DROP_ORDER):
            if table not in tables:
                continue
            columns = [d[1] for d in con.execute(f"PRAGMA table_info({table})")]
            col_list = ", ".join(columns)
            placeholders = ", ".join("?" for _ in columns)
            insert = f"INSERT INTO {table} ({col_list}) VALUES ({placeholders});"
            rows = con.execute(f"SELECT * FROM {table}").fetchall()  # noqa: S608
            parts.append(f"-- {table} ({len(rows)} rows)")
            # executemany-style expansion into literal SQL: D1's execute takes
            # one file of statements, so parameters must be inlined.
            batch: list[str] = []
            for row in rows:
                batch.append(
                    insert.replace(
                        placeholders,
                        ", ".join(quote(row[c]) for c in columns),
                    )
                )
                if len(batch) >= 500:
                    parts.extend(batch)
                    batch.clear()
            parts.extend(batch)
            parts.append("")

        args.out.write_text("\n".join(parts))
        size_mb = args.out.stat().st_size / 1e6
        print(f"Wrote {args.out} ({size_mb:.1f} MB, {len(tables)} tables)")
    finally:
        con.close()


if __name__ == "__main__":
    main()
